export const TOKEN_VERIFICATION_REQUESTED = 'TOKEN_VERIFICATION_REQUESTED';
export const LOG_IN_REQUESTED = 'LOG_IN_REQUESTED';
export const LOG_OUT_REQUESTED = 'LOG_OUT_REQUESTED';
export const AUTH_STATUS_CHANGED = 'AUTH_STATUS_CHANGED';
